import type { Metadata } from "next";
import "./globals.css";
import { Footer, Navbar } from "@/components/index";
import { DataContextProvider } from "@/context/dataContext";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Car Showroom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en w-screen">
      <body className="w-full relative overflow-x-hidden">
        <DataContextProvider>
          <Toaster />
          <Navbar />
          {children}
          <Footer />
        </DataContextProvider>
      </body>
    </html>
  );
}
